(part "NE182UEEP6AMP"
    (packageRef "NE182UEEP6AMP")
    (interface
        (port "A1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "A2") (portType INOUT))
        (port "P1" (symbPinId 3) (portName "P1") (portType INOUT))
        (port "P2" (symbPinId 4) (portName "P2") (portType INOUT))
        (port "R1" (symbPinId 5) (portName "R1") (portType INOUT))
        (port "R2" (symbPinId 6) (portName "R2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "NE182UEEP6AMP")
    (property "Mouser_Part_Number" "611-NE182UEEP6AMP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/NE182UEEP6AMP?qs=u2NJ%252B70r0go80sgN5CJXfg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Pushbutton Switch DPDT Standard Through Hole, Right Angle, 250 V")
    (property "Datasheet_Link" "https://www.littelfuse.com/assetdocs/littelfuse-c-k-pushbutton-ne18-series-datasheet?assetguid=eaa0cce0-0711-4a80-a25e-fa5683c64f06")
    (property "symbolName1" "NE182UEEP6AMP")
)
